name: Update Match Data

on:
  repository_dispatch:
    types: [update_match]
  workflow_dispatch:
    inputs:
      winner:
        description: 'Winner name'
        required: true
      loser:
        description: 'Loser name'
        required: true
      winnerScore:
        description: 'Winner score'
        required: true
      loserScore:
        description: 'Loser score'
        required: true

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Update match data
        run: |
          node update-data.js '${{ toJson(github.event.client_payload) }}' '${{ toJson(github.event.inputs) }}'

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data.json
          git diff --staged --quiet || git commit -m "Update match data: ${{ github.event.client_payload.winner || github.event.inputs.winner }} vs ${{ github.event.client_payload.loser || github.event.inputs.loser }}"
          git push